### PR TITLE
Remove Donald & Goofy's extra 50 starting AP

### LINKED ISSUE #43: Donald & Goofy AP Bonus
Seems like Donald and Goofy also gets 50 starting AP. Is that a bug or a feature?

### PR DESCRIPTION
**Pull request by 1234567890num**
Fixes #43

### CODE REVIEW

**Comment by paulblessing** [comment]
I've been working on #102 to make starting AP customizable, with a setting for Sora and a setting for Donald/Goofy. Should achieve the same end goal where someone can set Donald/Goofy to 0 if they want, or can set them higher if they want.

**Comment by 1234567890num** [comment]
> I believe Donald starts with 5 AP and Goofy starts with 4AP normally, so I think if this is to change, it should be to those values.

Donald's 5 AP and Goofy's 4 AP are part of their level 1 stats, not starting stats. With the current code, Donald starts with 55 AP and Goofy starts with 54 AP.

**Comment by zlittlefield** [comment]
This is getting changed into a new option to set starting ap for all main party members, it will allow for donald/goofy to start with their minimum ap, or do what it's doing now. If you disagree, feel free to discuss here.

**Comment by 1234567890num** [comment]
I honestly did not know how I managed to unknowingly merged this when I was trying to make another branch, but it changes nothing substantial so 🤷‍♂️ 

A new option for starting AP will be nice would be a better solution.

**Pull request merged**
