### PR TITLE
Support for KH3D bgm

### PR DESCRIPTION
**Pull request by o0DemonBoy0o**
just added the stuff to for the KH DDD HD bgm

### CODE REVIEW

**Comment by o0DemonBoy0o** [comment]
did some other changes for what should work to get kh1 music randomization going.

**Comment by tommadness** [comment]
`git branch pcCmdMenu` - Creates a new branch that is an exact copy of the current branch
`git reset --hard b206933` - Reverts master branch to "Setup method for Custom BGM" commit, keeping the new commits on `pcCmdMenu`
`git checkout pcCmdMenu` - To start working in the new `pcCmdMenu` branch

**Comment by o0DemonBoy0o** [comment]
cheif, i've been editing things by downloading the files from the fork i made and reuploading them through the site.
i kinda have no idea how to do what you just explained

**Comment by o0DemonBoy0o** [comment]
i'll just uhhh, download the original randomCmdMenu.py and put that back in my fork

**Comment by tommadness** [comment]
Looks good, thank you so much! The cmd menu changes can be merged when the necessary changes are made to the mod manager bridge.

**Pull request merged**
